/// Generates a specialized WGSL compute shader for fused dequant+matmul.
///
/// Each quantization type gets a dedicated pipeline with the dequantization
/// logic baked into the WGSL source at shader module creation time. This
/// avoids runtime branching and lets the GPU driver optimize aggressively.
///
/// The generated shader follows this structure:
///   bindings: input[f32], weight[u32], output[f32], config[uniform]
///   workgroup_size: 64
///   one output element per invocation

pub struct QuantShaderSpec {
    /// GGML type ID (for documentation in the generated source)
    pub type_name: &'static str,
    /// Number of elements per quantization block
    pub block_size: u32,
    /// Bytes per quantization block in the packed format
    pub block_bytes: u32,
    /// Whether the shader needs a 256-element local dequant buffer
    pub use_local_buffer: bool,
    /// WGSL function body that dequantizes one block.
    /// Variables available:
    ///   `block_byte_off: u32` — byte offset of the block in the weight array (local buf mode)
    ///   `off: u32` — byte offset of the block (inline mode)
    ///   `buf: ptr<function, array<f32, 256>>` — local buffer (if use_local_buffer)
    pub dequant_body: &'static str,
}

/// Core WGSL source template.
const TEMPLATE_PREFIX: &str = r#"// Auto-generated fused dequant+matmul shader for {TYPE_NAME}.
// Quantization: {TYPE_NAME}, block={BLOCK_SIZE} elems, {BLOCK_BYTES} bytes/block.
//
// Generated by bitty-wgpu-runtime matmul_shader module.

@group(0) @binding(0) var<storage, read> input: array<f32>;
@group(0) @binding(1) var<storage, read> weight: array<u32>;
@group(0) @binding(2) var<storage, read_write> output: array<f32>;
@group(0) @binding(3) var<uniform> config: MatMulConfig;

struct MatMulConfig {{
    in_dim: u32,
    out_dim: u32,
}}

const QK: u32 = {BLOCK_SIZE}u;
const BLOCK_BYTES: u32 = {BLOCK_BYTES}u;

fn f16_to_f32(h: u32) -> f32 {{
    let sign = h & 0x8000u;
    let exp = (h >> 10u) & 0x1Fu;
    let mant = h & 0x3FFu;
    if (exp == 0u) {{
        return select(
            f32(mant) * 5.960464477539063e-08,
            -f32(mant) * 5.960464477539063e-08,
            sign != 0u,
        );
    }}
    let m = f32(mant) / 1024.0 + 1.0;
    let e = f32(exp) - 15.0;
    return select(m * exp2(e), -m * exp2(e), sign != 0u);
}}

{DEQUANT_FUNCTIONS}

@compute @workgroup_size(64)
fn main(@builtin(global_invocation_id) gid: vec3<u32>) {{
    let j = gid.x;
    if (j >= config.out_dim) {{ return; }}
    let in_dim = config.in_dim;
    let blocks_per_row = (in_dim + QK - 1u) / QK;
    var sum: f32 = 0.0;
{LOOP_BODY}
    output[j] = sum;
}}
"#;

/// Template for block-iterating loop body with local dequant buffer.
const LOOP_WITH_BUF: &str = r#"    var buf: array<f32, {BLOCK_SIZE}>;
    for (var bi = 0u; bi < blocks_per_row; bi++) {{
        let blk = j * blocks_per_row + bi;
        let block_byte_off = blk * BLOCK_BYTES;
        {DEQUANT_BODY}
        let x_start = bi * QK;
        let n = min(QK, in_dim - x_start);
        for (var k = 0u; k < n; k++) {{
            sum += input[x_start + k] * buf[k];
        }}
    }}"#;

/// Template for inline (no local buffer) dequant loop.
const LOOP_INLINE: &str = r#"    for (var bi = 0u; bi < blocks_per_row; bi++) {{
        let blk = j * blocks_per_row + bi;
        let off = blk * BLOCK_BYTES;
        let x_start = bi * QK;
        let n = min(QK, in_dim - x_start);
        {DEQUANT_BODY}
    }}"#;

/// Shader specs for each supported quantization type.
pub fn quant_shader_spec(ggml_type: u32) -> Option<QuantShaderSpec> {
    match ggml_type {
        // Q4_K — 256-element superblocks, 4-bit quants (144 bytes)
        12 => Some(QuantShaderSpec {
            type_name: "Q4_K",
            block_size: 256,
            block_bytes: 144,
            use_local_buffer: true,
            dequant_body: Q4K_DEQUANT,
        }),
        // Q5_K — 256-element superblocks, 5-bit quants (176 bytes)
        13 => Some(QuantShaderSpec {
            type_name: "Q5_K",
            block_size: 256,
            block_bytes: 176,
            use_local_buffer: true,
            dequant_body: Q5K_DEQUANT,
        }),
        // Q6_K — 256-element superblocks, 6-bit quants (210 bytes)
        14 => Some(QuantShaderSpec {
            type_name: "Q6_K",
            block_size: 256,
            block_bytes: 210,
            use_local_buffer: true,
            dequant_body: Q6K_DEQUANT,
        }),
        // Q4_0 — 32-element blocks, 4-bit round-to-nearest (18 bytes)
        2 => Some(QuantShaderSpec {
            type_name: "Q4_0",
            block_size: 32,
            block_bytes: 18,
            use_local_buffer: false,
            dequant_body: Q4_0_DEQUANT,
        }),
        // Q8_0 — 32-element blocks, 8-bit signed quants (34 bytes)
        8 => Some(QuantShaderSpec {
            type_name: "Q8_0",
            block_size: 32,
            block_bytes: 34,
            use_local_buffer: false,
            dequant_body: Q8_0_DEQUANT,
        }),
        _ => None,
    }
}

/// Generate complete WGSL source for a quantization type.
pub fn generate_matmul_shader(ggml_type: u32) -> Option<String> {
    let spec = quant_shader_spec(ggml_type)?;
    let dequant_fns = match ggml_type {
        12 | 13 => GET_SCALE_MIN_K4.to_string(),
        14 => String::new(),
        _ => String::new(),
    };

    let loop_body = if spec.use_local_buffer {
        LOOP_WITH_BUF
            .replace("{BLOCK_SIZE}", &spec.block_size.to_string())
            .replace("{DEQUANT_BODY}", spec.dequant_body)
    } else {
        LOOP_INLINE.replace("{DEQUANT_BODY}", spec.dequant_body)
    };

    let source = TEMPLATE_PREFIX
        .replace("{TYPE_NAME}", spec.type_name)
        .replace("{BLOCK_SIZE}", &spec.block_size.to_string())
        .replace("{BLOCK_BYTES}", &spec.block_bytes.to_string())
        .replace("{DEQUANT_FUNCTIONS}", &dequant_fns)
        .replace("{LOOP_BODY}", &loop_body);

    Some(source)
}

// ─── Dequantization function bodies ───

/// get_scale_min_k4 helper shared by Q4_K and Q5_K.
const GET_SCALE_MIN_K4: &str = r#"
fn get_scale_min_k4(j: u32, s0: u32, s1: u32, s2: u32) -> vec2<u32> {
    var sc: u32;
    var m: u32;
    if (j < 4u) {
        let shift = j * 8u;
        sc = (s0 >> shift) & 0x3Fu;
        m = (s1 >> shift) & 0x3Fu;
    } else {
        let j4 = j - 4u;
        let shift = j4 * 8u;
        let high = (s2 >> shift) & 0x0Fu;
        let low = (s1 >> (j * 6u - 24u)) & 0x30u;
        sc = high | low;
        let m_high = (s2 >> (shift + 4u)) & 0x0Fu;
        let m_low = (s0 >> (j * 6u - 24u)) & 0x30u;
        m = m_high | m_low;
    }
    return vec2(sc & 0x3Fu, m & 0x3Fu);
}
"#;

const Q4K_DEQUANT: &str = r#"        let base_u32 = block_byte_off / 4u;
        let d_u16 = weight[base_u32] & 0xFFFFu;
        let d = f16_to_f32(d_u16);
        let dmin_u16 = (weight[base_u32] >> 16u) & 0xFFFFu;
        let dmin = f16_to_f32(dmin_u16);
        let s0 = weight[base_u32 + 1u];
        let s1 = weight[base_u32 + 2u];
        let s2 = weight[base_u32 + 3u];
        let qs_base = base_u32 + 4u;
        for (var j = 0u; j < QK; j += 64u) {
            let is = (j / 64u) * 2u;
            let (sc1, m1) = get_scale_min_k4(is, s0, s1, s2);
            let (sc2, m2) = get_scale_min_k4(is + 1u, s0, s1, s2);
            let d1 = d * f32(sc1);
            let md1 = dmin * f32(m1);
            let d2 = d * f32(sc2);
            let md2 = dmin * f32(m2);
            let q_off = is / 2u * 32u;
            for (var l = 0u; l < 32u; l++) {
                let qw = weight[qs_base + q_off / 4u + l / 2u];
                let shift = (l & 1u) * 16u;
                let b = (qw >> shift) & 0xFFu;
                buf[j + l] = d1 * f32(b & 0x0Fu) - md1;
                buf[j + 32u + l] = d2 * f32(b >> 4u) - md2;
            }
        }"#;

const Q5K_DEQUANT: &str = r#"        let base_u32 = block_byte_off / 4u;
        let d_u16 = weight[base_u32] & 0xFFFFu;
        let d = f16_to_f32(d_u16);
        let dmin_u16 = (weight[base_u32] >> 16u) & 0xFFFFu;
        let dmin = f16_to_f32(dmin_u16);
        let s0 = weight[base_u32 + 1u];
        let s1 = weight[base_u32 + 2u];
        let s2 = weight[base_u32 + 3u];
        var u1: u32 = 1u;
        var u2: u32 = 2u;
        for (var j = 0u; j < QK; j += 64u) {
            let is = (j / 64u) * 2u;
            let (sc1, m1) = get_scale_min_k4(is, s0, s1, s2);
            let (sc2, m2) = get_scale_min_k4(is + 1u, s0, s1, s2);
            let d1 = d * f32(sc1);
            let md1 = dmin * f32(m1);
            let d2 = d * f32(sc2);
            let md2 = dmin * f32(m2);
            let qs_offset = is / 2u * 32u;
            let qh_offset = j / 8u;
            for (var l = 0u; l < 32u; l++) {
                let qs_byte = qs_offset + l;
                let qs_u32 = base_u32 + 12u + qs_byte / 4u;
                let qs_shift = (qs_byte & 3u) * 8u;
                let qs = (weight[qs_u32] >> qs_shift) & 0xFFu;
                let qh_byte = qh_offset + l / 8u;
                let qh_u32 = base_u32 + 4u + qh_byte / 4u;
                let qh_shift = (qh_byte & 3u) * 8u;
                let qh = (weight[qh_u32] >> qh_shift) & 0xFFu;
                let qh_bit = qh >> (l & 7u);
                let lo = (qs & 0x0Fu) | (((qh_bit & u1) << 4u));
                let hi = (qs >> 4u)    | (((qh_bit & u2) << 4u));
                buf[j + l] = d1 * f32(lo) - md1;
                buf[j + 32u + l] = d2 * f32(hi) - md2;
            }
            u1 = u1 << 2u;
            u2 = u2 << 2u;
        }"#;

const Q6K_DEQUANT: &str = r#"        let u32_base = block_byte_off / 4u;
        var sc: array<u32, 4>;
        sc[0] = weight[u32_base + 48u]; sc[1] = weight[u32_base + 49u];
        sc[2] = weight[u32_base + 50u]; sc[3] = weight[u32_base + 51u];
        let d_u16 = weight[u32_base + 52u] & 0xFFFFu;
        let d = f16_to_f32(d_u16);
        let d_tbl: array<f32, 8> = array(
            d * f32(i32(sc[0u] & 0xFFu)) - 32.0, d * f32(i32((sc[0u] >> 8u) & 0xFFu)) - 32.0,
            d * f32(i32((sc[0u] >> 16u) & 0xFFu)) - 32.0, d * f32(i32((sc[0u] >> 24u) & 0xFFu)) - 32.0,
            d * f32(i32(sc[1u] & 0xFFu)) - 32.0, d * f32(i32((sc[1u] >> 8u) & 0xFFu)) - 32.0,
            d * f32(i32((sc[1u] >> 16u) & 0xFFu)) - 32.0, d * f32(i32((sc[1u] >> 24u) & 0xFFu)) - 32.0,
        );
        for (var l = 0u; l < 32u; l++) {
            let ql0 = weight[u32_base + l / 2u] & 0xFFFFu;
            let ql1 = (weight[u32_base + l / 2u] >> 16u) & 0xFFFFu;
            let low_ql = (ql0 >> ((l & 1u) * 8u)) & 0xFFu;
            let high_ql = (ql1 >> ((l & 1u) * 8u)) & 0xFFu;
            let qh_byte = (weight[u32_base + 32u] >> ((l & 1u) * 8u)) & 0xFFu;
            let q1 = (low_ql & 0x0F) | (((qh_byte >> 0) & 3) << 4);
            let q2 = (high_ql & 0x0F) | (((qh_byte >> 2) & 3) << 4);
            let q3 = (low_ql >> 4) | (((qh_byte >> 4) & 3) << 4);
            let q4 = (high_ql >> 4) | (((qh_byte >> 6) & 3) << 4);
            let is = l / 16u;
            buf[l + 0u] = d_tbl[is + 0u] * f32(q1);
            buf[l + 32u] = d_tbl[is + 4u] * f32(q2);
            buf[l + 64u] = d_tbl[is + 8u] * f32(q3);
            buf[l + 96u] = d_tbl[is + 12u] * f32(q4);
        }"#;

const Q4_0_DEQUANT: &str = r#"        let u32_off = off / 4u;
        let d_u16 = weight[u32_off] & 0xFFFFu;
        let d = f16_to_f32(d_u16);
        let n_bytes = (n + 1u) / 2u;
        for (var k = 0u; k < n_bytes; k++) {
            let byte_off = off + 2u + k;
            let u32_idx = byte_off / 4u;
            let shift = (byte_off & 3u) * 8u;
            let b = (weight[u32_idx] >> shift) & 0xFFu;
            let lo = i32(b & 0x0Fu) - 8;
            let hi = i32(b >> 4u) - 8;
            let lo_idx = x_start + k;
            let hi_idx = x_start + 16u + k;
            if (lo_idx < in_dim) { sum += input[lo_idx] * f32(lo) * d; }
            if (hi_idx < in_dim) { sum += input[hi_idx] * f32(hi) * d; }
        }"#;

const Q8_0_DEQUANT: &str = r#"        let u32_off = off / 4u;
        let d_u16 = weight[u32_off] & 0xFFFFu;
        let d = f16_to_f32(d_u16);
        for (var k = 0u; k < n; k++) {
            let byte_off = off + 2u + k;
            let u32_idx = byte_off / 4u;
            let shift = (byte_off & 3u) * 8u;
            let q_val = i32((weight[u32_idx] >> shift) & 0xFFu);
            if (q_val > 127) { q_val = q_val - 256; }
            sum += input[x_start + k] * f32(q_val) * d;
        }"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_all_quant_types_generate() {
        for t in [2u32, 8, 12, 13, 14] {
            let src = generate_matmul_shader(t);
            assert!(src.is_some(), "no shader for type {t}");
            let src = src.unwrap();
            assert!(src.contains("var<storage, read> input"), "missing bindings for type {t}");
            assert!(src.contains("fn main"), "missing main for type {t}");
        }
    }

    #[test]
    fn test_q4k_uses_buffer() {
        let src = generate_matmul_shader(12).unwrap();
        assert!(src.contains("var buf: array<f32, 256>"), "Q4_K should use local buffer");
    }

    #[test]
    fn test_q4_0_no_buffer() {
        let src = generate_matmul_shader(2).unwrap();
        assert!(!src.contains("var buf:"), "Q4_0 should NOT use local buffer");
    }
}
